name = "TikzPictures"
uuid = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
license = "MIT"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.0"
LaTeXStrings = "1.1"
